version: '3'

services:
  web:
    build: .
    command: python3 manage.py runserver 000.0.0.0:8000
    volumes:
    - .:/kokurcho_site
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: nouchka/sqlite3:latest
    ports:
    - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db.sqlite3'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    volumes:
      - ./db/:/root/db/