# Generated by Django 4.0.4 on 2022-05-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kokurcho_app', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='comm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
